version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /opt/docker/spring-boot:/app
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
