name: Deploy Spring Boot Application

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'  # Use 'adopt' or 'temurin' or any other distribution

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build and push Docker image
      run: |
        docker build -t spring-boot .
        docker save spring-boot | bzip2 | ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "bunzip2 | docker load"
      env:
        DOCKER_BUILDKIT: 1

    - name: Deploy to Server
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "docker-compose -f /opt/docker/spring-boot/docker-compose.yml up -d"
      env:
        DOCKER_BUILDKIT: 1

    - name: Clean up Gradle Cache
      run: ./gradlew clean

    - name: Clean up Docker
      run: docker system prune -af
